# SEO Values
title: "Journal de bord de Doran Voss"
description: "Le raid de Kessel en moins de 12 Parsecs !"
logo: https://draculatheme.com/static/icons/pack-1/045-dracula.svg


show_downloads: false
show_header: false
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
